//
// Created by 冉宝宝 on 11/12/2017.
//

#ifndef MYFS_ERRNUM_H
#define MYFS_ERRNUM_H
#define VIRTUAL_DISK_OPERATION_SUCCESS 0
#define VIRTUAL_DISK_FILE_WRITE_ERROR -1
#define VIRTUAL_DISK_FILE_CLOSE_ERROR -2
#endif //MYFS_ERRNUM_H
